window.MATHCHAMPS_TEST_CONFIG = {
  // Isi pilihan cabang secara manual di daftar ini. Cabang akan muncul sebagai dropdown di halaman test.
  branches: [
    "Mathpreneur ONLINE",
    "Banjarmasin - Gatot Subroto Plus",
    "Bogor - Permata",
    "Bekasi - Cibubur",
    "Bekasi - Harapan Indah Plus",
    "Bekasi - Mustika Jaya",
    "Bogor - Braja Mustika",
    "Bogor - Pajajaran",
    "Bogor - Sawojajar",
    "Cilacap - S. Parman",
    "Cilegon - PCI",
    "Denpasar - Melati",
    "Depok - Sukmajaya",
    "Depok - Margonda Plus",
    "Gombong - Puring",
    "Jakarta Barat - Taman Anggrek Mall",
    "Jakarta Barat - Kemanggisan",
    "Jakarta Pusat - Cempaka Putih",
    "Jakarta Selatan - Jagakarsa",
    "Jakarta Selatan - Kebayoran Baru",
    "Jakarta Selatan - Petukangan",
    "Jakarta Timur - Ciracas",
    "Jakarta Timur - Condet",
    "Jakarta Timur - Duren Sawit",
    "Jakarta Utara - Sunter",
    "Kroya - Jenderal Sudirman",
    "Malang - Klojen",
    "Medan - Iskandar Muda Plus",
    "Metro - Sudirman",
    "Padang - Gajah Mada",
    "Palembang - Basuki Rahmat",
    "Palu - Jenderal Sudirman",
    "Purbalingga - Letkol Isdiman",
    "Purwokerto - Kombas",
    "Sangatta - Yos Sudarso",
    "Semarang - Banyumanik",
    "Serang - Ahmad Yani",
    "Sidoarjo - Trunojoyo",
    "Solo - Gajahmada",
    "Sukabumi - Sudirman",
    "Sukoharjo - Veteran",
    "Surabaya - Jemursari",
    "Surabaya - MERR Plus",
    "Tangerang - Citymall",
    "Tangerang Selatan - Bintaro",
    "Tangerang Selatan - Pamulang",
    "Tangerang Selatan - Pamulang Plus",
    "Yogyakarta - Sagan",
    "Yogyakarta - Terban Plus",
    "Yogyakarta - Wirobrajan",
    "Klaten - Merbabu",
    "Bandung - Kota Baru Parahyangan Plus",
    "Depok - Kelapa Dua",
    "Garut - Perintis",
    "Bandung - MTC Plus",
    "Bekasi - Bintara",
    "Bekasi - Summarecon",
    "Cilegon - PCI Plus",
    "Depok - Cinere",
    "Depok - Cinere Plus",
    "Jakarta Selatan - Tebet",
    "Jakarta Timur - Rawamangun",
    "Karawang - Resinda Park Mall",
    "Kendari - Abdullah Silondae",
    "Tangerang - Citra Raya",
    "Tangerang - Gading Serpong",
    "Tangerang Selatan - Bintaro Plus",
    "Tangerang Selatan - Golden Madrid",
    "Jakarta Utara - Koja",
    "Salatiga - Moh. Yamin"
  ],

  // Isi nama teacher secara manual di daftar ini. Nama akan muncul sebagai dropdown di halaman test.
  teachers: [
    "Bernadeta Christina Rifka Tantyana",
    "Afriliany Dian Oetari",
    "Muhammad Ihsan Saladin",
    "Siska Miati Jatiningsih",
    "Tri Mulyani",
    "Nurul Mumtaza",
    "Raihan Anwar Thaha",
    "Zulfa Amalina",
    "Asep Muzayyin",
    "Hafiz Haedar",
    "Sri Runi Andriani",
    "Muhammad Rafi Ashedanansyah",
    "Neli Syifain Nimah",
    "Clarissa",
    "Karomani",
    "Dewi Ayu Sukmawati Sugiyanto",
    "Imelda doharta aritonang",
    "Riadah Masita",
    "Ahmad Rosyid Syamsudin",
    "Indah Tiara",
    "Sandy Puspita Della",
    "Haura Putri Fortuna",
    "Selvira Azizah Putri",
    "Jihad Akbar",
    "Sukma Nurfitri",
    "Natika Rahayu",
    "Iffaabdillah Kinasih",
    "Nazirotun Nikmah",
    "Putri Meilia Asmara",
    "Mutiara Ratu Salsabila",
    "Tasya Anisah Rizqi",
    "Aulia Nurul Ilmi Sakkir",
    "Laila Fajriati Qodriah",
    "Ayu Cintiya Usmawati",
    "Rifaldho Muhammad Rizki",
    "Aurora Nesya Salsabilla",
    "Putri Anggraeni",
    "Rizki Hadinata Trisno",
    "Yumna Alhay Munajaeti",
    "Salma Muftiyah",
    "Riana",
    "Syaifunnisa Puspa Kencana",
    "Shaila",
    "Shabrina Quraisy",
    "Susi Suntari",
    "Lusita",
    "Fitri Apriliawati",
    "MOZA IMANI KAUTSAR",
    "Ananda Dwiyani Susilo",
    "Nabila Aryuni",
    "Anisya Ananda",
    "SHINTA NUR PRATIWI RAMADHANI",
    "Lesta Milva Musvira",
    "Firastika Eka Nurhayati",
    "Jihan Munawaroh",
    "Wilda Nurul Qolbi",
    "Lukmanul Hakim",
    "Noviona Marathus Sholihah",
    "Damara Salsabila",
    "Kesha Diandra Salsabila Shafa",
    "Nabhan Muflih",
    "Suci Indah Sari",
    "Basyir Iskandarsyah",
    "Asri Ginawati",
    "Arkan Fadhlan",
    "Dwi Ratna Andriani",
    "Edwina Hangganararas",
    "Khansa Dezi Tabina",
    "Muhammad Alwi Dahlan",
    "Muhammad Alimuddien Rasyid",
    "Evelin Theresia Panjaitan",
    "Radaza Putri Hanaki",
    "Febby Diansyah",
    "Devran Perdana Malik",
    "Riko Ade Sanjaya",
    "Alfanda Wiratama",
    "Suryatna Sacadibrata",
    "Zahratul Fitri Masyhudah",
    "Ainin Nahdlia Zahra",
    "Clarinta Shankendra",
    "Nurul Atsna Qonita",
    "Nur Saidah",
    "Verani Rosa Belinda",
    "Purwitasari Ranudya Wardhani",
    "Puteri Bulqis Azhari",
    "Nuzullaila Sitorus Pane",
    "Zhekkar Harummy Pramesty",
    "Najmah Shabibah",
    "Tata Frarisia",
    "Handinda Putri Agustina",
    "Afifah Dewanti",
    "Nur Sangadah",
    "Olvie Chlaudya Tuhusula",
    "Stephanie Quensi Abrahams",
    "Khairunnisa Ramadhani Adam",
    "Kurnia Nurbaiti",
    "Sri Wulandari Mubarochah"
  ],

  // Hasil test otomatis tersimpan ke dashboard online. Bagian ini tidak perlu diubah.
  supabaseUrl: "https://suifgsvtcbrawzdhyuhk.supabase.co",
  storageKey: "sb_publishable_9BdHYLcpIS0B6Z92WxXf_Q_WpWBswLB",
  resultPrefix: "api/math-champs-toys-craft-online-results-20260623",

  // Opsional: paste link Google Spreadsheet pribadi jika admin ingin menaruh arsip manual.
  spreadsheetUrl: "",

  // Opsional lama: hanya dipakai jika suatu saat ingin membaca CSV Google Sheet eksternal.
  resultsSheetCsvUrl: ""
};
